# Generated by Django 5.0 on 2023-12-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('details', models.TextField()),
                ('remark', models.TextField()),
                ('created_user', models.TextField()),
                ('updated_user', models.TextField()),
                ('deleted_user', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField()),
                ('deleted_at', models.DateField()),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
