# Generated by Django 5.0 on 2023-12-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_role_is_approve_user_alter_role_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='test_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='test_user',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
